### ISSUE TITLE
How to assertEquals the output vs expected

### ISSUE THREAD

**Issue by mikedelgaudio** [mikedelgaudio/CS-555-GEDCOM#13]
The output is a PrettyTable that we will need to somehow either string match or compare files to ensure the output of our program matches the expected.

**Comment by PaulGurman** [comment]
Maybe we should consider a class structure so the data is accessible through data members while having a display function that uses prettytable.

**Comment by mikedelgaudio** [comment]
> Maybe we should consider a class structure so the data is accessible through data members while having a display function that uses prettytable.

I agree, I am not to familiar with OOP with Python but if you think it could really help us out I think it'd be awesome.
